version: '3.2'

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: docker.arvancloud.ir/postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres