version: '3.2'

services:
  web:
    build: .
    container_name: django1
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - lab_docker_network
  database:
    image: docker.arvancloud.ir/postgres:16-alpine
    container_name: db1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - lab_docker_network

networks:
  lab_docker_network: